[package]
authors.workspace = true
edition.workspace = true
name              = "near-da-sidecar"
version.workspace = true

[dependencies]
anyhow                       = "1.0.75"
axum                         = "0.6"
clap                         = { version = "4.4", features = [ "derive" ] }
futures-util.workspace       = true
futures.workspace            = true
hex.workspace                = true
itertools.workspace          = true
moka                         = { version = "*", features = [ "future" ] }
near-da-http-api-data        = { path = "../../crates/http-api-data" }
near-da-primitives           = { path = "../../crates/primitives" }
near-da-rpc                  = { path = "../../crates/da-rpc" }
serde                        = "1"
serde_json                   = "1.0.108"
tokio                        = { version = "1", features = [ "full" ] }
tower                        = "0.4"
tower-http                   = { version = "0.4", features = [ "trace", "normalize-path" ] }
tracing-subscriber.workspace = true
tracing.workspace            = true
